WITH CITIES AS 
(select city  from (
   SELECT city,count(distinct order_id)
   FROM `efood2022-352312.main_assesment.orders` 
   group by city
    having count(distinct order_id)>1000
)z
)
,USER_FREQ_BREAK AS (
  SELECT CITY,USER_ID,
  COUNT(CASE WHEN CUISINE = 'Breakfast' THEN ORDER_ID END)/COUNT(DISTINCT CASE WHEN CUISINE = 'Breakfast' THEN USER_ID END)  AS BREAK_FREQ
  FROM `efood2022-352312.main_assesment.orders` 
  WHERE CUISINE = 'Breakfast' AND CITY IN (SELECT * FROM CITIES)
  group by city,USER_ID
)
,ARITHM1 AS (SELECT CITY,COUNT(USER_ID) AS USER_ID FROM USER_FREQ_BREAK WHERE BREAK_FREQ> 3 GROUP BY CITY)
,PAR1 AS (SELECT CITY,COUNT(USER_ID) AS USER_ID FROM USER_FREQ_BREAK  GROUP BY CITY)

,FREQ_BREAK AS (
  SELECT CITY,USER_ID,
  COUNT(ORDER_ID)/COUNT(DISTINCT USER_ID)  AS FREQ
  FROM `efood2022-352312.main_assesment.orders` 
  WHERE  CITY IN (SELECT * FROM CITIES)
  group by city,USER_ID
)
,ARITHM2 AS (SELECT CITY,COUNT(USER_ID) AS USER_ID FROM FREQ_BREAK WHERE FREQ> 3 GROUP BY CITY)
,PAR2 AS (SELECT CITY,COUNT(USER_ID) AS USER_ID FROM FREQ_BREAK  GROUP BY CITY)
,CITIES_BREAK AS (
SELECT CITY FROM (
    SELECT  CITY,COUNT(ORDER_ID) ORDER_ID 
    FROM `efood2022-352312.main_assesment.orders` WHERE CUISINE = 'Breakfast' GROUP BY CITY 
)Z ORDER BY ORDER_ID DESC  LIMIT 5
)
,FINAL_1 AS (SELECT * FROM (
SELECT 
 A.CITY
 ,SUM(CASE WHEN CUISINE = 'Breakfast' THEN AMOUNT END)/COUNT(CASE WHEN CUISINE = 'Breakfast' THEN ORDER_ID END ) AS BREAKFAST_BASKET  
 ,SUM(AMOUNT)/COUNT(ORDER_ID) AS EFOOD_BASKET
 ,COUNT(CASE WHEN CUISINE = 'Breakfast' THEN ORDER_ID END)/COUNT(DISTINCT CASE WHEN CUISINE = 'Breakfast' THEN A.USER_ID END ) AS BREAKFAST_FREQ  
 ,COUNT(ORDER_ID)/COUNT(DISTINCT A.USER_ID) AS EFOOD_FREQ
 ,B.USER_ID/ C.USER_ID AS BREAKFST_USERS3_FREQ
 ,D.USER_ID/ E.USER_ID AS EFOOD_USERS3_FREQ
 FROM `efood2022-352312.main_assesment.orders`  AS  A
 LEFT JOIN ARITHM1 AS B ON A.CITY = B.CITY
 LEFT JOIN PAR1 AS C ON A.CITY = C.CITY
 LEFT JOIN ARITHM2 AS D ON A.CITY = D.CITY
 LEFT JOIN PAR2 AS E ON A.CITY = E.CITY
 WHERE A.CITY IN (SELECT * FROM CITIES)
GROUP BY A.CITY,B.USER_ID, C.USER_ID , D.USER_ID, E.USER_ID
) Z WHERE CITY IN (SELECT * FROM CITIES_BREAK)
)


---2
,ARITHM2_2 AS (SELECT CITY,SUM(ORDER_ID) AS ORDER_ID 
FROM (
SELECT *,ROW_NUMBER() OVER (PARTITION BY CITY ORDER BY ORDER_ID DESC) RN FROM (
SELECT CITY,USER_ID,COUNT(ORDER_ID) AS ORDER_ID
 FROM `efood2022-352312.main_assesment.orders`
 GROUP BY CITY,USER_ID 
) Z 
)W 
WHERE W.RN<=10
GROUP BY CITY
)
,PARANOM2_2 AS (SELECT CITY,COUNT(ORDER_ID) AS ORDER_ID
 FROM `efood2022-352312.main_assesment.orders`
 GROUP BY CITY
)
,FINAL_2 AS 
(SELECT A.CITY,A.ORDER_ID/B.ORDER_ID FROM ARITHM2_2 AS A LEFT JOIN PARANOM2_2 AS B ON A.CITY = B.CITY)

--SELECT * FROM FINAL_1

--SELECT * FROM FINAL_2
